#!/usr/bin/env bash
# A script that installs nginx server on an ubuntu linux distro.
# The installed server listens to port 80 (HTTP) for connection
# And serves a default page index.html on the HTTP  GET request.

sudo apt-get update -y

sudo apt-get install nginx -y
sudo chown -R $USER:$USER /var/www
sudo chmod -R 755 /var/www
echo 'Hello World!' | tee /var/www/html/index.html

sudo service nginx restart
