#!/usr/bin/env bash
# This script displays To infinity and beyond indefinitely, with a 2-second pause between each iteration
while true # This is an infinite loop
do
  echo "To infinity and beyond" # This prints the message
  sleep 2 # This pauses for 2 seconds
done
